print('--- Part 1 ---')
n=input('Enter 1000-9999: ')
a=int(n[0])
b=int(n[1])
c=int(n[2])
d=int(n[3])
print('a=%d, b=%d, c=%d, d=%d'%(a,b,c,d))
print('\n---- Part 2 ---')
print('Biggest number is %d'%(max(a,b,c,d)))